### ISSUE TITLE
p.319 図版04のスペース

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#613]
```css
.hamburgerMenu ul{
  display: none;
}
.hamburgerMenu.js-opened ul{
  display: block;
}
```

要素セレクターと波括弧の間はスペースが入るはず

```css
.hamburgerMenu ul {
  display: none;
}
.hamburgerMenu.js-opened ul {
  display: block;
}
```
